# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "acba658132da60be2408850e95613111"
name = "QuickWish"
handle = "quickwish"
application_url = "https://quick-wish.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, unauthenticated_read_product_tags, unauthenticated_read_customers, unauthenticated_read_product_listings"

[auth]
redirect_urls = [
  "https://quick-wish.onrender.com/auth/callback",
  "https://quick-wish.onrender.com/auth/shopify/callback",
  "https://quick-wish.onrender.com/api/auth/callback"
]

[pos]
embedded = false
